# Generated by Django 5.0.8 on 2024-08-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="blog_images/"),
        ),
    ]
