# Generated by Django 5.0.8 on 2024-08-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_blog_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
