# Generated by Django 5.0.8 on 2024-08-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_alter_blog_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
